Update us_validation.yml

diff --git a/.github/workflows/us_validation.yml b/.github/workflows/us_validation.yml
--- a/.github/workflows/us_validation.yml
+++ b/.github/workflows/us_validation.yml
@@ -14,20 +14,33 @@ on:
         type: string
 jobs:     
 
-
-  validate_destination:
+  validate_version:
     runs-on: self-hosted
     steps:
-
-    - name: validate for dev
-      if: ${{ github.event.inputs.destination == 'artifact_dev' }}
-      run: | 
-        echo "is for development"
+    - name: validating default version
+      run: |
         if ${{ github.event.inputs.version == '0.0.0' }} 
         then 
           echo "🚫 invalid version ${{ github.event.inputs.version }}"
           exit 1
         fi
+    - name: validating empty version
+      run: |
+        if ${{ github.event.inputs.version == '' }} 
+        then 
+          echo "🚫 invalid empty version "
+          exit 1
+        fi
+
+  validate_destination:
+    needs: validate_version
+    runs-on: self-hosted    
+    steps:
+
+    - name: validate for dev
+      if: ${{ github.event.inputs.destination == 'artifact_dev' }}
+      run: | 
+        echo "is for development"        
 
     - name: validate for prod_vnv
       if: ${{ github.event.inputs.version == 'artifact_prod_vnv' }}
